### ISSUE TITLE
Overview not scrollable

### ISSUE THREAD

**Issue by Scumpeter** [SecUSo/privacy-friendly-food-tracker#56]
When the list of items in the overview screen exceeds the screen size, some items can't be seen anymore. Please make this screen scrollabe, so all items can be accessed.

Device: Pixel 3 (with Android 9) 
Food Tracker Version: 1.0.1 (from Fdroid)

**Comment by kauk** [comment]
I am able to reproduce this problem.
Device: Motorola Moto G5
Food Tracker Version: latest from Play Store
Apart from this issue I like the app very much. Thank you, developers.

**Comment by ec-nebi** [comment]
Same problem and it sounds like a very important feature, being able to see what you entered.

Device: Samsung S5
OS: LineageOS
Version: 1.0.1 (Fdroid)

**Comment by Seegras** [comment]
I can see exactly 4 items I entered on a Samsung GT I9195, resolution 960x540. And can't scroll. 

OS: LineageOS
Version: 1.0.1 (Fdroid)

**Comment by account-sxf** [comment]
I also encountered this.  The issue is compounded when you rotate the device and it changes to landscape mode.  Please implement scrolling.
