### ISSUE TITLE
KeyGeneration seems to not always work

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-food-tracker#58]

**Comment by IlyaMax** [comment]
yes same to me, generatePassphrase doesn't work actually and I think it would be better to substitute calling thread into loader/asynctask because GenerateKeyActivity crashes after screen rotation

**Comment by Kamuno** [comment]
Fixed via fd1c35e85416d8fefdbffb0f93cb5345186c3b34
