### ISSUE TITLE
[BUG] daily overview not scrollable

### ISSUE THREAD

**Issue by nottheend** [SecUSo/privacy-friendly-food-tracker#74]
After entering few entries for one day, it is not possible to scroll down to the latest entry.
Refering to the day view.

Therefore adding further entries is possible, but editing isn't

**Comment by christianfl** [comment]
Already fixed in upstream, see https://github.com/SecUSo/privacy-friendly-food-tracker/issues/56

**Comment by nottheend** [comment]
Ok nice, thanks for the info

**Comment by nottheend** [comment]
It's really much more fun to use the app with this fix. Säthanks for the effort 🎉
