### ISSUE TITLE
Weekly Statistics  not displayed or calculated correctly 

### ISSUE THREAD

**Issue by Goat-Beard** [SecUSo/privacy-friendly-food-tracker#79]
Platform: Sony Xperia XA2 H3113 
LineageOS 17.1 (5th Jun 2020) 
The statistics page displays data incorrectly. See screen shot
![Screenshot_20200706-104153_Food_Tracker](https://user-images.githubusercontent.com/43937312/86580534-c592cd80-bf76-11ea-9650-b738ea3f8a67.png)
Selected the week ending 04/07 resulted in the screenshot above.
The display heading is for 28/06/20 - 04/07/20 the display and daily average is for 29/06 - 05/07 divided by 8 (should be 7)
29/6 - 1953
30/6 - 1928
01/7 - 1767
02/7 - 1870
03/7 - 2401
04/7 - 1906
05/7 - 1876
 Total 13701 ÷ 8 = 1712 (should be ÷ 7 = 1957)
The figure for 03/7 is displayed under 02/7

**Comment by christianfl** [comment]
See also: https://github.com/SecUSo/privacy-friendly-food-tracker/issues/71
