### ISSUE TITLE
Privacy Friendly Backup support?

### ISSUE THREAD

**Issue by ngleb** [SecUSo/privacy-friendly-food-tracker#88]
Are there any plans on adding support for backup with the Privacy Friendly Backup? I tried installing both apps, but Backup doesn't show anything.

Both apps were installed from Google Play. Version of Backup is 1.0 and Food Tracker is 1.1.0.

**Comment by Kamuno** [comment]
Yes, this is indeed planned. We just released the Backup App and will add this functionality to all Privacy Friendly Apps over time. We'll keep you updated 👍

**Comment by Bobhasgithub** [comment]
Any new updates to the backup compatability?
Alternatively is there another way to backup/transfer the database to a new phone?
I don't want to lose all the food-data I accumulated over time...

Thanks in Advance Bob.
